---
title: "A clean and uncluttered template"
author: "Alban Ott"
date: "`r format(Sys.time(), '%d %B %Y')`"
mail: "ott.alban@gmail.com"
output:
  epuRate::epurate:
    toc: TRUE
    number_sections: FALSE
    code_folding: "hide"
---

## load packages

```{r}
library(geosphere)
library(ggplot2); theme_set(theme_bw())
library(ggiraph)
library(sf)
library(raster)
library(OpenStreetMap)
library(dplyr)
library(lubridate)
library(gtools)
```


<!-- ## Load data -->

<!-- ### wastewater -->

<!-- ```{r} -->
<!-- stations = read.csv2("./data/obepine/19-04-2021-stations.csv",dec=".") -->
<!-- dim(stations) -->

<!-- #keep only high quality data -->
<!-- stations_HQ = stations %>% -->
<!--   # arrange(desc(IPQDE)) %>%  -->
<!--   # head() -->
<!--   filter(IPQDE==2) -->
<!-- dim(stations_HQ) -->

<!-- head(stations_HQ) -->
<!-- ``` -->

<!-- ### Laposte -->

<!-- ```{r} -->
<!-- laposte = read.csv2("./data/laposte/laposte_hexasmal.csv") %>%  -->
<!--   mutate(Longitude = sub(pattern = "^(.*),(.*)$", replacement = "\\1", x = coordonnees_gps) %>% as.numeric()) %>%  -->
<!--   mutate(Latitude = sub(pattern = "^(.*),(.*)$", replacement = "\\2", x = coordonnees_gps) %>% as.numeric()) -->

<!-- head(laposte) -->
<!-- ``` -->

<!-- ### Associate stations to the closest city -->

<!-- ```{r} -->
<!-- indiv_stations = stations %>%  -->
<!--   select(Station, Code_Sandre, Longitude_station, Latitude_station) %>%  -->
<!--   distinct() %>%  -->
<!--   filter(!is.na(Longitude_station)) %>%  -->
<!--   filter(!is.na(Latitude_station)) -->
<!-- ``` -->

<!-- search for the closet city according to laposte and assume it belongs there -->
<!-- ```{r} -->

<!-- distgeo = function(poste, Longitude_station, Latitude_station){ -->
<!--   distance=distm(c(poste["Longitude"], poste["Latitude"]), -->
<!--                  c(Longitude_station, Latitude_station)) -->
<!--   return(distance) -->
<!-- } -->


<!-- indiv_stations$Code_commune_INSEE="" -->
<!-- for(i in 1:nrow(indiv_stations)){ -->
<!--   Latitude_station=indiv_stations[i,"Longitude_station"]#the data titles are false -->
<!--   Longitude_station=indiv_stations[i,"Latitude_station"]#the data titles are false -->
<!--   dist=apply(laposte[,c("Longitude","Latitude")],1,distgeo, Longitude_station=Longitude_station, Latitude_station=Latitude_station) -->
<!--   mindist=which.min(dist) -->
<!--   indiv_stations[i,"Code_commune_INSEE"]=laposte[mindist,"Code_commune_INSEE"] -->
<!-- } -->
<!-- ``` -->



<!-- join the 2 tables -->
<!-- ```{r} -->
<!-- stations_laposte = stations %>%  -->
<!--   left_join(indiv_stations) %>%  -->
<!--   left_join(laposte) -->
<!-- ``` -->



<!-- Add department based on zip code -->
<!-- ```{r} -->
<!-- stations_laposte = stations_laposte %>%  -->
<!--   mutate(Departement=as.numeric(sub(pattern = "[0-9]{3}$", replacement = "", x = Code_postal))) -->
<!-- ``` -->


### Load the ICU data
```{r}
ICU = read.csv2("./data/ICU/donnees-hospitalieres-covid19-2021-04-23-20h12.csv") %>%
  rename(Departement=dep) %>%
  mutate(Departement=sub(pattern = "^0", replacement = "", x=Departement)) %>% 
  mutate(Date=ymd(jour)) %>% 
  filter(sexe==0)



```



<!-- ## Save the table -->
<!-- ```{r} -->
<!-- write.csv2(stations_laposte, file = "./output/stations_laposte.csv") -->
<!-- ``` -->



## visualization {.tabset}


```{r}
stations_laposte=read.csv2(file = "./output/stations_laposte.csv")
```


```{r}

decorate_station_by_departement = stations_laposte %>% 
  distinct(Departement, Station) %>% 
  group_by(Departement) %>% 
  mutate(col_by_station=as.character(1:n())) %>% 
  ungroup() %>% 
  arrange(Departement)

stations_laposte=stations_laposte %>% 
  mutate(IPQDE_c=as.character(IPQDE)) %>% 
  left_join(decorate_station_by_departement) %>% 
  mutate(Date=ymd(Date)) %>% 
  mutate(Departement=as.character(Departement)) %>% 
  as.data.frame()
```

```{r}
stations_laposte_ICU = bind_rows(stations_laposte,
                                 ICU)
```


### All departement

```{r, fig.height=320, fig.width=10}
ggplot(stations_laposte_ICU, aes_string("Date","Indicateur"))+
  geom_point(aes_string(group="Code_Sandre", col="col_by_station", shape="IPQDE_c"))+
  geom_line(aes_string(group="Code_Sandre", col="col_by_station"))+
  geom_point(aes_string(y="rea"), col="red")+
  geom_line(aes_string(y="rea"), col="red")+
  scale_colour_viridis_d()+
  guides( color = FALSE)+
  facet_grid(Departement~., scales = "free_y")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
   scale_y_continuous(
     name = "Obepine",
     sec.axis = sec_axis(~.*1, name="# pers réa")
   )
  
```


```{r, results='asis'}
for(dep in mixedsort(unique(stations_laposte_ICU$Departement))){
  if(!is.na(dep)){
  cat(paste0("\n\n\n### ",dep,"\n\n"))
  
  p=ggplot(stations_laposte_ICU %>% filter(Departement==dep), aes_string("Date","Indicateur"))+
    geom_point(aes_string(group="Code_Sandre", col="col_by_station", shape="IPQDE_c"))+
    geom_line(aes_string(group="Code_Sandre", col="col_by_station"))+
    geom_point(aes_string(y="rea"), col="red")+
    geom_line(aes_string(y="rea"), col="red")+
    scale_colour_viridis_d()+
    guides( color = FALSE)+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
    scale_y_continuous(
      name = "Obepine",
      sec.axis = sec_axis(~.*1, name="# pers réa")
    )+
    ggtitle(paste0("departement: ",dep))
  
  print(p)

  cat("\n\n")
  }
}
```


